config/routes.rb
Rails.application.routes.draw do
  namespace :api do
    scope '/mentions' do
      get '/users', to: 'mentions#users', as: :mentionable_users
      get '/recordings', to: 'mentions#recordings', as: :mentionable_recordings
    end
  end

  get '/todo', to: 'docs#todo'
  get '/faq',  to: 'docs#faq'
  get '/tos',  to: 'docs#tos'

  devise_for :users, path: '', path_names: {
    sign_in: 'login',
    sign_out: 'logout',
    sign_up: 'signup',
  }

  resources :shouts, except: :show do
    member do
      patch '/bump', to: 'shouts#bump', as: :bump
    end
    
    collection do
      patch '/dismiss', to: 'shouts#dismiss', as: :dismiss
    end
  end

  get '/settings', to: 'settings#edit', as: :settings
  patch '/settings', to: 'settings#update'

  resources :tags, only: %i|index show|

  get '/new', to: 'recordings#new', as: :new_recording
  get '/:id/edit', to: 'recordings#edit', as: :edit_recording
  
  get '/@:id', to: 'users#show', as: :user

  resources :replies, only: %i|update destroy|, as: :reply
  resources :recordings, only: %i|create|
  
  # since these are the same route and we can't have duplicate methods
  # we force it to not create one for the later ones and just use them identically
  get '/:id/replies', to: 'replies#show', as: :replies
  post '/:id/replies', to: 'replies#create', as: nil

  get '/:id', to: 'recordings#show', as: :recording
  patch '/:id', to: 'recordings#update'
  
  root to: 'recordings#index'
end

app/models/shout.rb
# == Schema Information
#
# Table name: shouts
#
#  id         :integer          not null, primary key
#  link       :string
#  shouted_at :datetime
#  url        :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  user_id    :integer
#

class Shout < ApplicationRecord
  MIN_TIME_ACTIVE = 6.hours

  NotAvailableError = Class.new(ArgumentError)

  class << self
    def show?
      active && !dismissed?
    end

    def active
      order(shouted_at: :desc).limit(1).take
    end
  
    def available?
      !active || expired?
    end

    private

    def dismissed?
      return false unless Current.user&.shout_dismissed_at
      return true unless active
      Current.user.shout_dismissed_at >= active.shouted_at
    end

    def expired?
      ((Time.current - active.shouted_at) / 1.hour).round.hours >= MIN_TIME_ACTIVE
    end
  end

  default_scope { order(shouted_at: :desc) }

  before_create { raise NotAvailableError unless Shout.available? }
  after_create { update shouted_at: created_at }

  has_rich_text :content
  belongs_to :user, default: -> { Current.user }

  validates :content, presence: true

  def bump!
    raise NotAvailableError unless bumpable?
    update shouted_at: Time.current
  end

  def bump
    bump!
    true
  rescue NotAvailableError
    false
  end

  def active?
    Shout.active == self
  end

  def bumpable?
    Shout.available?
  end
end

app/controllers/shouts_controller.rb
class ShoutsController < ApplicationController
  before_action :authenticate_user!, except: :index
  before_action :set_shout, only: %i|edit update destroy bump|
  before_action :authenticate_shouter!, only: %i|edit update destroy bump|
  before_action :ensure_available, only: %i|new create|

  def dismiss
    Current.user.update!(shout_dismissed_at: Time.current)
  end

  def new
    @shout = Shout.new
  end

  def create
    if Shout.create(shout_params)
      redirect_to shouts_path
    else
      render 'edit'
    end
  end

  def edit
  end

  def update
    if @shout.update(shout_params)
      redirect_to shouts_path
    else
      render 'edit'
    end
  end

  def bump
    @shout.bump!
    redirect_to shouts_path
  end

  def destroy
    @shout.destroy
    redirect_to shouts_path
  end

  private

  def set_shout
    @shout = Shout.find(params[:id])
  end

  def authenticate_shouter!
    unless @shout.user == Current.user
      redirect_to root_path
    end
  end

  def ensure_available
    redirect_to shouts_path unless Shout.available?
  end

  def shout_params
    params.require(:shout).permit(:content, :url)
  end
end

app/helpers/shouts_helper.rb
module ShoutsHelper
  def active_shout_expires_in
    distance_of_time_in_words(Time.current, Shout.active.shouted_at + Shout::MIN_TIME_ACTIVE)
  end
end

app/views/shouts/_form.erb
<% if action_name == 'edit' %>
  <div class="container mx-auto my-2 p-2 rounded border-2 bg-gray-200 text-gray-700">
    <% if shout.active? %>
      This shout <strong>is currently locked in.</strong> Shouting will unlock again in <strong><%= active_shout_expires_in %></strong>.
    <% elsif Shout.available? %>
      This shout is expired, but you can <%= link_to 'bump it', bump_shout_path(shout), method: :patch, class: 'visible-link' %> to make it appear on top of the page again. You could also <%= link_to 'create a new shout', new_shout_path, class: 'visible-link' %>.
    <% else %>
      This shout is inactive. As another shout is locked in, it <strong>cannot be bumped now</strong>.
    <% end %>
  </div>
<% end %>

<%= fgh_form(model: shout) do |f| %>
  <div class="my-2 rounded border-2 bg-gray-200">
    <div class="mb-2">
      <%= f.label :content, class: 'block font-bold ml-2 text-lg' %>
      <%= f.rich_text_area :content %>
    </div>

    <div>
      <%= f.fancy_text_field :url, 'URL (Optional)', icon: :link %>
    </div>
  </div>

  <%= f.submit %>

  <% if action_name == 'edit' %>
    or <%= link_to 'delete it', shouts_path(shout), method: :delete, data: { confirm: 'Are you sure?' }, class: 'visible-link' %>
  <% end %>
<% end %>

app/views/shouts/_shout.html.erb
<%= cache shout do %>
  <% if shout.active? %>
    <div class="bg-green-600 text-white rounded-t-lg font-bold px-2 py-1">
      <% if Shout.available? %>
        Active
      <% else %>
        Active / Locked In
      <% end %>
    </div>
  <% end %>
  <div class="shadow-lg p-2 mb-2 bg-white flex">
    <div class="flex-grow">
      <%= shout.content %>
    </div>

    <% if Current.user == shout.user %>
      <%= link_to 'Edit', edit_shout_path(shout), class: 'visible-link pr-1' %>
      <%= link_to 'Bump', bump_shout_path(shout), method: :patch, class: 'visible-link pr-1' if shout.bumpable? %>
      <%= link_to 'Delete', shout_path(shout), method: :delete, data: { confirm: 'Are you sure?' }, class: 'visible-link' %>
    <% end %>
  </div>
<% end %>

app/views/shouts/dismiss.js.erb
document.querySelector('#shout').remove();
document.body.classList.remove('shout-showing');

app/views/shouts/edit.html.erb
<%= rp 'form', shout: @shout %>

app/views/shouts/index.html.erb
<div class="container mx-auto my-2 p-2 rounded border-2 bg-gray-200 text-gray-700">
  <h2 class="font-bold text-2xl">
    Shouts
  </h2>

  <p class="mb-2">Shouts are a system for <strong>quickly notifying people of new updates</strong> in your project. A shout will appear at the top of the page and be <strong>visible to everyone until dismissed.</strong></p>

  <p class="mb-2"><strong>Only one shout can be active at a time.</strong> When a shout is created, <strong>it will be "locked in" for <%= Shout::MIN_TIME_ACTIVE.inspect %>.</strong> During the locked in phase, no one can create new shouts. After that, the shout remains visible, but <strong>anyone can create a new shout to replace it.</strong></p>

  <p class="mb-2">If there is no locked-in shout, you can <strong>create a new shout, or bump an old shout</strong> of your own.</p>

  <p class="mb-2">Abusing the shout system <strong>will result in access being removed.</strong></p>
</div>

<div class="mb-2">
  <% if Shout.available? %>
    <h2 class="font-bold text-2xl">
      Create Shout
    </h2>

    <% if Shout.active %>
      The current shout is no longer locked in. You can <%= link_to 'replace it with a new shout', new_shout_path, class: 'visible-link' %>.
    <% else %>
      Nobody has shouted yet. <%= link_to 'Create the first!', new_shout_path, class: 'visible-link' %>.
    <% end %>
  <% else %>
    <h2 class="font-bold text-2xl">
      Shouting Locked
    </h2>

    <% if Current.user == Shout.active.user %>
      <strong>Your shout is currently locked-in.</strong> 
      
      Shouting will unlock again in <strong><%= active_shout_expires_in %></strong>. 
      
      You can 
      <%= link_to 'edit your shout', edit_shout_path(Shout.active), class: 'visible-link' %> 
      or 
      <%= link_to 'delete it', shout_path(Shout.active), method: :delete, data: { confirm: 'Are you sure you want to delete this shout?' }, class: 'visible-link' %>.
    <% else %>
      <strong><%= Shout.active.user.username %></strong>'s shout is <strong>currently locked in.</strong> Shouting will unlock again in <strong><%= active_shout_expires_in %></strong>.
    <% end %>
  <% end %>
</div>

<% if Current.user %>
  <div class="mb-2">
    <h2 class="font-bold text-2xl">
      Your Shouts
    </h2>

    <% if Current.user.shouts.empty? %>
      You've never shouted.

      <% if Shout.available? %>
        But hey, it's <%= link_to 'never too late to learn!', new_shout_path, class: 'visible-link' %>
      <% end %>
    <% else %>
      <%= rc 'shouts/shout', Current.user.shouts %>
    <% end %>
  </div>
<% end %>

app/views/shouts/new.html.erb
<%= rp 'form', shout: @shout %>