config/routes.rb
Rails.application.routes.draw do
  namespace :api do
    scope '/mentions' do
      get '/users', to: 'mentions#users', as: :mentionable_users
      get '/recordings', to: 'mentions#recordings', as: :mentionable_recordings
    end
  end

  get '/todo', to: 'docs#todo'
  get '/faq',  to: 'docs#faq'
  get '/tos',  to: 'docs#tos'

  devise_for :users, path: '', path_names: {
    sign_in: 'login',
    sign_out: 'logout',
    sign_up: 'signup',
  }

  resources :shouts, except: :show do
    member do
      patch '/bump', to: 'shouts#bump', as: :bump
    end
    
    collection do
      patch '/dismiss', to: 'shouts#dismiss', as: :dismiss
    end
  end

  get '/settings', to: 'settings#edit', as: :settings
  patch '/settings', to: 'settings#update'

  resources :tags, only: %i|index show|

  get '/new', to: 'recordings#new', as: :new_recording
  get '/:id/edit', to: 'recordings#edit', as: :edit_recording
  
  get '/@:id', to: 'users#show', as: :user

  resources :replies, only: %i|update destroy|, as: :reply
  resources :recordings, only: %i|create|
  
  # since these are the same route and we can't have duplicate methods
  # we force it to not create one for the later ones and just use them identically
  get '/:id/replies', to: 'replies#show', as: :replies
  post '/:id/replies', to: 'replies#create', as: nil

  get '/:id', to: 'recordings#show', as: :recording
  patch '/:id', to: 'recordings#update'
  
  root to: 'recordings#index'
end

app/models/recording.rb
# == Schema Information
#
# Table name: recordings
#
#  id              :integer          not null, primary key
#  banner_has_text :boolean
#  color           :string
#  discord         :string
#  featured_at     :datetime
#  github          :string
#  name            :string
#  pokecomm        :string
#  published_at    :datetime
#  relic_castle    :string
#  replies_count   :integer          default(0)
#  slug            :string
#  type            :string
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#  user_id         :integer
#
# Indexes
#
#  index_recordings_on_slug  (slug) UNIQUE
#

class Recording < ApplicationRecord
  include Types

  include Authored, Content, Colorable, Downloadable, IndexListable, Featurable, Mentionable, Named, Paintable, Publishable, SocialLinkable, Reactable, Replyable, Taggable

  def term
    type.downcase
  end

  delegate :sti_style, to: :class

  def self.sti_style_of(type)
    type.classify.constantize.sti_style
  end

  def to_partial_path
    'recordings/recording'
  end

  def to_trix_content_attachment_partial_path
    'recordings/recording'
  end
end

app/models/recording/colorable.rb
module Recording::Colorable
  extend ActiveSupport::Concern

  included do
    serialize :color, Color

    validates :color,
      presence: true,
      format: { with: /#[0-9a-fA-F]{6}/ }

    before_validation :set_default_color, on: :create
  end
  
  def colorable_class_name
    lightness = color.light? ? 'light' : 'dark'
    "recording--colorized-#{lightness}"
  end

  private

  DEFAULT_COLORS = %w|
    #EC6363
    #ff912b
    #FFAD33
    #15aa70
    #009de6
    #156eC1
    #ff7cb3
    #bb50e5
  |

  def set_default_color(force: false)
    return if color && !force
    self.color = DEFAULT_COLORS.sample
  end
end

app/models/recording/content.rb
module Recording::Content
  extend ActiveSupport::Concern

  included do
    has_rich_text :description
    has_rich_text :content
    before_validation :create_default_content, on: :create

    validates :content,
      presence: true,
      allow_blank: false
  end

  private

  DEFAULT_MESSAGES = {
    text: "You can replace this with your TERM's FIELD!",
    gallery: "You can replace this text with images for your TERM's FIELD! Try dragging and dropping images into the editor.",
  }

  FIELD_SEPARATOR = '<br>'

  def create_default_content(force: false)
    return if content.present? && !force

    self.content = default_content_items.map do |title, type|
      title = title.to_s
      message = DEFAULT_MESSAGES[type]
        .gsub('FIELD', title)
        .gsub('TERM', term)

      <<~HTML
        <h1>#{title.titlecase}</h1>
        <div>#{message}</div>
      HTML
    end.join(FIELD_SEPARATOR)
  end
end

app/models/recording/downloadable.rb
module Recording::Downloadable
  extend ActiveSupport::Concern

  included do
    has_many :downloads
    accepts_nested_attributes_for :downloads, allow_destroy: true
  end
end

app/models/recording/featurable.rb
module Recording::Featurable
  def featured=(bool)
    if bool
      self.featured_at = DateTime.now
    else
      self.featured_at = nil
    end
  end
end

app/models/recording/index_listable.rb
module Recording::IndexListable
  extend ActiveSupport::Concern

  included do
    scope :on_index, -> params {
      published
        .of_type(params[:type])
        .order(updated_at: :desc)
        .includes(:author, :avatar_attachment, :tags)
    }
  end
end

app/models/recording/named.rb
module Recording::Named
  extend ActiveSupport::Concern

  included do
    extend FriendlyId
    friendly_id :name, use: :slugged

    validates :name, presence: true
  end

  def slug=(slug)
    super(no_pokemon_prefix(slug))
  end

  private

  def no_pokemon_prefix(slug)
    slug.sub(/^pokemon[-_ ]/, '') if slug
  end
end

app/models/recording/paintable.rb
module Recording::Paintable
  extend ActiveSupport::Concern
  include Rails.application.routes.url_helpers

  included do
    has_one_attached :avatar
    has_one_attached :banner
  end

  def avatar_path
    if avatar.attached?
      rails_blob_path(avatar, disposition: 'attachment', only_path: true) 
    end
  end

  def banner_path
    if banner.attached?
      rails_blob_path(banner, disposition: 'attachment', only_path: true) 
    end
  end
end

app/models/recording/publishable.rb
module Recording::Publishable
  extend ActiveSupport::Concern

  included do
    scope :published, -> {
      if Current.user
        where('published_at IS NOT NULL OR user_id = ?', Current.user.id)
      else
        where.not(published_at: nil)
      end
    }
  end

  def published?
    published_at.present?
  end

  def publish!
    update! published_at: Time.now
  end

  def published=(value)
    if value && value.to_i != 0
      self.published_at = Time.now
    else
      self.published_at = nil
    end
  end
end

app/models/recording/replyable.rb
module Recording::Replyable
  extend ActiveSupport::Concern

  included do
    has_many :replies
  end
end

app/models/recording/social_linkable.rb
module Recording::SocialLinkable
  LINK_FIELDS = %i|github discord pokecomm|

  def any_links?
    LINK_FIELDS.any? { |f| self[f].present? }
  end
end

app/models/recording/taggable.rb
module Recording::Taggable
  extend ActiveSupport::Concern

  included do
    has_many :taggings, dependent: :destroy
    has_many :tags, through: :taggings
  end

  def tag_list
    tags.collect(&:name).join(', ')
  end

  def tag_list=(tag_list)
    self.tags = tag_list.split(/,/).map do |name|
      name = name.strip.delete('#')
      Tag.find_or_create_by(name: name)
    end
  end
end

app/models/recording/types.rb
module Recording::Types
  extend ActiveSupport::Concern

  LIST = %w|Game Tutorial Resource|

  def self.count
    LIST.count
  end

  included do
    scope :of_type, -> type {
      if Recording.type?(type)
        where(type: type.classify)
      else
        all
      end
    }

    Recording::Types::LIST.each do |type|
      scope type.downcase.pluralize, -> {
        of_type(type)
      }
    end

    validates :type,
      presence: true,
      inclusion: { in: Recording::Types::LIST }
  end

  class_methods do
    def type?(type)
      type&.classify.in?(LIST)
    end
  end
end

app/controllers/recordings_controller.rb
class RecordingsController < ApplicationController
  before_action :set_recording, except: %i|index new create|
  before_action :authenticate_user!, except: %i|index show|
  before_action :authenticate_published!, only: %i|show|
  before_action :authenticate_author!, only: %i|edit update destroy|

  def index
    @recordings = Recording.on_index(params)

    respond_to do |format|
      format.html {}
      # TODO MAJOR HACK
      # this is NOT json, but idk how to send type JS in axios, soooo we have this mess
      # fix it ASAP!
      format.json {
        render partial: 'list', locals: { recordings: @recordings }, formats: [:html]
      }
    end
  end

  def new
    @recording = Recording.new
  end

  def create
    @recording = Recording.create(recording_params)
    
    if @recording.persisted?
      redirect_to recording_path(@recording)
    else
      if @recording.type
        render "new_#{@recording.type.downcase}"
      else
        redirect_to root_path
      end
    end
  end

  def show
  end

  def edit
  end

  def update
    if @recording.update(recording_params)
      redirect_to recording_path(@recording)
    else
      render 'edit'
    end
  end

  private

  def recording_params
    params.require(:recording).permit(:name, :tag_list, :published, :type, :description, :content, :avatar, :banner, :github, :discord, :pokecomm, :relic_castle, downloads_attributes: [])
  end

  def authenticate_published!
    return if @recording.editable?
    redirect_to root_path unless @recording.published?
  end

  def authenticate_author!
    redirect_to root_path unless @recording.editable?
  end

  def set_recording
    @recording = Recording.friendly.find(params[:id])
  end
end

app/helpers/recordings_helper.rb
module RecordingsHelper
  def metadata_for(recording)
    user = recording.author
    color = recording.sti_style[:color]

    tag.div [
      tag.span(recording.term.capitalize, class: "text-white p-1 rounded mr-1 text-sm font-semibold bg-#{color}"),
      tag.span('by ', class: 'text-gray-600'),
      link_to(user.username, user_path(user.username), class: 'text-gray-700'),
      rp('tags/list', tags: recording.tags),
    ].join.html_safe
  end

  def each_recording_type_with_style
    Recording::Types::LIST.each do |type|
      yield(type, Recording.sti_style_of(type))
    end
  end
end

app/views/recordings/_header.html.erb
<% unless recording.published? %>
  <div class="bg-gray-200 px-2 py-3 border-2 rounded mb-2">
    <span class="font-semibold">Hey!</span> This <%= recording.term %> is currently unpublished! Click <%= link_to 'Edit', edit_recording_path(recording), class: 'btn btn-primary' %> and start editing when you're ready!
  </div>
<% end %>

<div class="flex items-center">
  <% if recording.avatar.attached? %>
    <%= image_tag recording.avatar, class: 'avatar' %>
  <% end %>

  <div class="flex-1">
    <div class="text-3xl font-bold">
      <%= recording.name %>
    </div>

    <%= metadata_for recording %>
  </div>

  <% if recording.editable? %>
    <%= link_to 'Edit', edit_recording_path(recording), class: 'btn btn-primary' %>
  <% end %>
</div>

<div class="mt-4">
  <%= active_link_to 'About', recording_path(@recording), class: 'tab-min', class_active: 'tab-min-active', active: :exact %>
  <%= active_link_to 'Replies', replies_path(@recording), class: 'tab-min', class_active: 'tab-min-active', active: :exact %>
</div>

app/views/recordings/_list.html.erb
<div id="recordings-list">
  <% if recordings.empty? %>
    <% if params[:type] %>
      <% sti_style = Recording.sti_style_of(params[:type]) %>
      <div class="flex items-center">
        <div class="mr-2 text-6xl text-white bg-<%= sti_style[:color] %> rounded-full h-24 w-24 flex items-center justify-center">
          <%= fa sti_style[:icon] %>
        </div>

        <div class="flex-1">
          <div class="text-2xl font-bold">
            There's nothing here yet...
          </div>

          <% if Current.user && params[:type] %>
            <div class="mt-2">
              <%= link_to new_recording_path(type: params[:type]), class: 'btn btn-primary' do %>
                Until now? Create a <%= params[:type].capitalize %>          
              <% end %>
            </div>
          <% end %>
        </div>
      </div>
    <% else %>
      <div class="text-2xl font-bold">
        There's nothing here yet...
      </div>
    <% end %>
  <% else %>
    <%= cache recordings do %>
      <div class="mb-4">
        <%= rc 'recording', recordings %>
      </div>
    <% end %>
  <% end %>
</div>

app/views/recordings/_recording.html.erb
<% # HACK 
  # TODO figure out how to get STI to always call the variable recording

  if defined?(game)
    recording = game
  elsif defined?(tutorial)
    recording = tutorial
  elsif defined?(resource)
    recording = resource
  end
%>

<%= cache recording do %>
  <div class="p-2" data-recording-id="<%= recording.id %>">
    <div class="rounded border">
      <div class="flex items-center p-2">
        
        <% if recording.avatar.attached? %>
          <%= link_to recording_path(recording) do %>
            <%= image_tag recording.avatar_path, class: 'avatar' %>
          <% end %>
        <% end %>

        <div class="flex-1">
          <div class="font-semibold">
            <%= link_to recording_path(recording) do %>
              <%= recording.name %>
            <% end %>
          </div>

          <%= metadata_for recording %>
        </div>

        <div class="text-center text-gray-700">
          <div class="text-3xl">
            <%= recording.replies_count %>
          </div>

          <div class="font-bold uppercase">
            Replies
          </div>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/recordings/edit.html.erb
<% unless @recording.published? %>
  <div class="bg-gray-200 px-2 py-3 border-2 rounded mb-2">
    When you're ready to publish your <%= @recording.term %>, check "<span class="font-semibold">Visibility</span>" in the General tab! Have fun editing!
  </div>
<% end %>

<%= fgh_form(model: @recording.becomes(Recording)) do |f| %>
  <div data-controller="tabs">
    <div>
      <button class="tab tab-active" type="button" data-tab="general" data-action="tabs#change" data-target="tabs.pill">
        General
      </button>

      <button class="tab" type="button" data-tab="write" data-action="tabs#change" data-target="tabs.pill">
        Write
      </button>

      <button class="tab" type="button" data-tab="paint" data-action="tabs#change" data-target="tabs.pill">
        Paint
      </button>

      <button class="tab" type="button" data-tab="links" data-action="tabs#change" data-target="tabs.pill">
        Links
      </button>

      <button class="tab" type="button" data-tab="downloads" data-action="tabs#change" data-target="tabs.pill">
        Downloads
      </button>
    </div>

    <div class="p-2 bg-gray-200 rounded">
      <div data-tab="general" data-target="tabs.panel">
        <%= f.fancy_text_field :name, "#{@recording.term.capitalize} Name",
          icon: :signature
        %>

        <%= f.fancy_text_field :tag_list, 'Tags',
          class: 'mt-2',
          icon: :tags,
          footnote: '(split on commas)'
        %>

        <div class="border-4 rounded p-2 mt-2">
          <label>
            <div class="font-semibold">
              Visibility
            </div>

            <%= f.check_box :published, checked: @recording.published? %>

            This is a published <%= @recording.term %>.
          </label>
        </div>
      </div>

      <div data-tab="write" data-target="tabs.panel" class="hidden">
        <%= f.rich_text_area :content %>
      </div>

      <div data-tab="paint" data-target="tabs.panel" class="hidden">
        <div class="border-4 rounded p-2">
          <%= f.label :avatar, class: 'block font-bold' %>
          <%= f.file_field :avatar %>
        </div>

        <div class="border-4 rounded p-2 mt-2">
          <%= f.label :banner, class: 'block font-bold' %>
          <%= f.file_field :banner %>
        </div>
      </div>

      <div data-tab="links" data-target="tabs.panel" class="hidden">
        <%= f.fancy_text_field :github, 'Github URL', 
          icon: [:github, :fab] 
        %>

        <%= f.fancy_text_field :discord, 'Discord Invite', 
          icon: [:discord, :fab], 
          class: 'mt-2' 
        %>
        
        <%= f.fancy_text_field :pokecomm, 'PokéCommunity Thread',
          icon: "https://pokecommunity.com/images/logo-notext.php?fill=4a5568",
          class: 'mt-2'
        %>

        <%# TODO proper icon for rc %>
        <%= f.fancy_text_field :relic_castle, 'Relic Castle Thread',
          icon: :leaf,
          class: 'mt-2'
        %>
      </div>

      <div data-tab="downloads" data-target="tabs.panel" class="hidden">
        coming soon!

        <% if false %>
          <div data-controller="downloads">
            <button type="button" data-action="downloads#prepend" class="btn btn-primary">
              <%= fa 'plus' %>
              New Download
            </button>

            <div data-target="downloads.template" class="hidden">
              <%= rp 'downloads/form', download: @recording.downloads.new %>
            </div>

            <div data-target="downloads.list">
              <% @recording.downloads.each do |download| %>
                <% if download.persisted? %>
                  <%= rp 'downloads/form', download: download %>
                <% end %>
              <% end %>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  </div>

  <div class="mt-2">
    <%= f.submit 'Save', data: { 'disable_with': 'Saving...' } %>
    <%= link_to 'Cancel', recording_path(@recording), class: 'btn', data: { confirm: 'Cancel editing?' } %>
  </div>
<% end %>

app/views/recordings/index.html.erb
<% unless Current.user %>
  <div class="container mx-auto my-2 p-2 flex items-center">
    <div class="flex-grow hidden md:block text-gray-600 text-2xl font-display font-bold">
      <%= zig_says_hi %>
    </div>

    <%= link_to 'Log In', new_user_session_path, class: 'btn' %>
    <%= link_to 'Sign Up', new_user_registration_path, class: 'btn btn-primary' %>
  </div>
<% end %>

<div class="flex items-center">
  <div class="flex-1" data-controller="filter" data-filter-url="<%= root_path %>">
    <form>
      <label>
        <input 
          type="radio" 
          name="filter"
          value="all"
          data-action="filter#change"
          <% unless Recording.type?(params[:type]) %>
            checked
          <% end %>  
        >

        All
      </label>
      <label>
        <input 
          type="radio" 
          name="filter" 
          value="game"
          data-action="filter#change"
          <% if params[:type]&.downcase == 'game' %>
            checked
          <% end %>
        >

        Games
      </label>
      <label>
        <input 
          type="radio" 
          name="filter" 
          value="tutorial"
          data-action="filter#change"
          <% if params[:type]&.downcase == 'tutorial' %>
            checked
          <% end %>
        >

        Tutorials
      </label>
      <label>
        <input 
          type="radio" 
          name="filter" 
          value="resource"
          data-action="filter#change"
          <% if params[:type]&.downcase == 'resource' %>
            checked
          <% end %> 
        >

        Resources
      </label>
    </form>
  </div>

  <% if Current.user %>
    <div class="relative" data-controller="dropdown">
      <button class="btn btn-primary" data-action="dropdown#toggle" data-target="dropdown.button">
        Create
        <%= fa 'caret-down' %>
      </button>

      <div class="w-full md:w-56 bg-white border-2 rounded-lg shadow-lg absolute right-0 hidden" style="top: 40px" data-target="dropdown.menu">
        <ul>
          <%= dropdown_link_to 'Create Game', new_recording_path(type: 'game') %>
          <%= dropdown_link_to 'Create Tutorial', new_recording_path(type: 'tutorial') %>
          <%= dropdown_link_to 'Create Resource', new_recording_path(type: 'resource') %>
        </ul>
      </div>
    </div>
  <% end %>
</div>

<%= rp 'list', recordings: @recordings %>

app/views/recordings/new.html.erb
<%= fgh_form(model: @recording.becomes(Recording)) do |f| %>
  <div class="border-b mb-4 pb-2">
    <div class="text-3xl font-light mb-1">
      Create Something
    </div>

    <div class="flex">
      <label>
        <input type="radio" name="type" value="Game" checked>
        Game/Hack
      </label>

      <label class="ml-2">
        <input type="radio" name="type" value="Tutorial">
        Tutorial
      </label>

      <label class="ml-2">
        <input type="radio" name="type" value="Resource">
        Resource
      </label>
    </div>
  </div>

  <div class="border-b mb-4 pb-2">
    <div class="mb-2">
      <div class="mb-1">
        <span class="font-semibold text-gray-800">
          Name
        </span>

        <span class="text-red-600">
          *
        </span>
      </div>

      <%= f.text_field :name, class: 'w-full border rounded p-1' %>
    </div>

    <div class="mb-2">
      <div class="mb-1">
        <span class="font-semibold text-gray-800">
          Description
        </span>
      </div>

      <%= f.rich_text_area :name %>
    </div>
  </div>

  <div class="p-2 bg-gray-200 rounded">
    <%= f.fancy_text_field :name, 'Game Name', 
      icon: :signature,
      autofocus: true
    %>


    <%= f.fancy_text_field :tag_list, 'Tags',
      class: 'mt-2',
      icon: :tags,
      footnote: 'suggested: pokeemerald, open world, etc (split on commas)'
    %>
  </div>

  <div class="mt-2">
    <%= f.submit 'Get Creating' %>
  </div>
<% end %>

app/views/recordings/show.html.erb
<%= rp 'recordings/header', recording: @recording %>

<% if @recording.banner.attached? %>
  </div> <!-- break out of container -->
      <%= image_tag @recording.banner, class: 'my-4 w-full' %>
  <div class="container mx-auto">
<% else %>
  <div class="my-6"></div>
<% end %>

<%= @recording.content %>

<% if @recording.any_links? %>
  <div class="border-2 bg-gray-200 text-gray-700 p-2 rounded my-4 flex items-center text-4xl">
    <% if @recording.github.present? %>
      <%= link_to @recording.github, target: :_blank, class: 'ml-1 mr-3', title: "#{@recording.name} on GitHub" do %>
        <%= fa :github, :fab %>
      <% end %>
    <% end %>

    <% if @recording.discord.present? %>
      <%= link_to @recording.discord, target: :_blank, class: 'ml-1 mr-3', title: "#{@recording.name} on Discord" do %>
        <%= fa :discord, :fab %>
      <% end %>
    <% end %>

    <% if @recording.pokecomm.present? %>
      <%= link_to @recording.pokecomm, target: :_blank, class: 'ml-1 mr-3', title: "#{@recording.name} on PokéCommunity" do %>
        <div style="width: 36px; height: 36px; background-image: url(https://pokecommunity.com/images/logo-notext.php?fill=4a5568); background-position: -8px -9px; background-size: 145%;"></div>
      <% end %>
    <% end %>

    <% if @recording.relic_castle.present? %>
      <%= link_to @recording.relic_castle, target: :_blank, class: 'ml-1 mr-3', title: "#{@recording.name} on Relic Castle" do %>
        <%= fa :leaf %>
      <% end %>
    <% end %>
  </div>
<% end %>