config/routes.rb
Rails.application.routes.draw do
  namespace :api do
    scope '/mentions' do
      get '/users', to: 'mentions#users', as: :mentionable_users
      get '/recordings', to: 'mentions#recordings', as: :mentionable_recordings
    end
  end

  get '/todo', to: 'docs#todo'
  get '/faq',  to: 'docs#faq'
  get '/tos',  to: 'docs#tos'

  devise_for :users, path: '', path_names: {
    sign_in: 'login',
    sign_out: 'logout',
    sign_up: 'signup',
  }

  resources :shouts, except: :show do
    member do
      patch '/bump', to: 'shouts#bump', as: :bump
    end
    
    collection do
      patch '/dismiss', to: 'shouts#dismiss', as: :dismiss
    end
  end

  get '/settings', to: 'settings#edit', as: :settings
  patch '/settings', to: 'settings#update'

  resources :tags, only: %i|index show|

  get '/new', to: 'recordings#new', as: :new_recording
  get '/:id/edit', to: 'recordings#edit', as: :edit_recording
  
  get '/@:id', to: 'users#show', as: :user

  resources :replies, only: %i|update destroy|, as: :reply
  resources :recordings, only: %i|create|
  
  # since these are the same route and we can't have duplicate methods
  # we force it to not create one for the later ones and just use them identically
  get '/:id/replies', to: 'replies#show', as: :replies
  post '/:id/replies', to: 'replies#create', as: nil

  get '/:id', to: 'recordings#show', as: :recording
  patch '/:id', to: 'recordings#update'
  
  root to: 'recordings#index'
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id                     :integer          not null, primary key
#  age                    :decimal(, )
#  email                  :string           default(""), not null
#  encrypted_password     :string           default(""), not null
#  gender                 :decimal(, )
#  location               :string
#  remember_created_at    :datetime
#  reset_password_sent_at :datetime
#  reset_password_token   :string
#  shout_dismissed_at     :datetime
#  username               :string           not null
#  created_at             :datetime         not null
#  updated_at             :datetime         not null
#
# Indexes
#
#  index_users_on_email                 (email) UNIQUE
#  index_users_on_reset_password_token  (reset_password_token) UNIQUE
#  index_users_on_username              (username) UNIQUE
#

class User < ApplicationRecord
  include Avatar, Customizable, Identity, Mentionable, Roles

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :recordings, dependent: :destroy
  has_many :featured_recordings, -> { where.not(featured_at: nil).order(featured_at: :desc) }, 
    class_name: 'Recording', 
    inverse_of: :author

  %w|Game Tutorial Resource|.each do |recording|
    has_many recording.downcase.pluralize.to_sym, -> { where type: recording },
      class_name: 'Recording',
      inverse_of: :author
  end

  has_many :replies, dependent: :destroy
  has_many :shouts, dependent: :destroy

  def mentionable_name
    username
  end
end

app/models/user/avatar.rb
module User::Avatar
  extend ActiveSupport::Concern
  include Rails.application.routes.url_helpers
  
  included do
    has_one_attached :avatar
    after_create :set_default_avatar
  end
  
  def avatar_path
    if avatar.attached?
      rails_blob_path(avatar, disposition: 'attachment', only_path: true) 
    end
  end
  
  private
  
  DEFAULT_AVATAR_PATH = Rails.root.join('app/assets/images/default_avatar.jpg')

  def set_default_avatar(force: false)
    return if avatar.attached? && !force
    avatar.attach(io: File.open(DEFAULT_AVATAR_PATH), filename: 'avatar.jpg')
  end
end

app/models/user/customizable.rb
module User::Customizable
  extend ActiveSupport::Concern

  included do
    has_rich_text :biography

    enum gender: {
      female:      0,
      male:        1,
      non_binary:  2,
      genderfluid: 3,
      other:       4,
    }
  end
end

app/models/user/identity.rb
module User::Identity
  extend ActiveSupport::Concern

  included do
    extend FriendlyId
    friendly_id :username

    validates :username, 
      presence: true, 
      format: { with: /\A[^\s!#$%^&*()（）=+;:'"\[\]\{\}|\\\/<>?,]+\z/ },
      length: { maximum: 50 },
      uniqueness: { case_sensitive: false }
  end
end

app/models/user/roles.rb
module User::Roles
  extend ActiveSupport::Concern

  included do
    has_many :roles do
      def primary
        sort.first unless empty?
      end
    end
  end

  def name_color
    roles.primary&.color
  end

  def role?(name)
    roles.find_by(name: name)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: :show

  def show
  end

  private

  def set_user
    @user = User.friendly.find(params[:id])
  end
end

app/views/users/_user.html.erb
<%= link_to user, class: 'font-bold' do %>
  @<span class="underline"><%= user.username %></span>
<% end %>

app/views/users/show.html.erb
<div class="flex mb-4">
  <div class="w-2/5 p-2">
    <%= image_tag @user.avatar_path, class: 'avatar avatar-lg' %>

    <% if @user.biography.present? %>
      <div class="mt-4 border-t-2 pt-2">
        <%= @user.biography %>
      </div>
    <% end %>
  </div>

  <div class="w-2/5 p-2">
    <div class="mr-1 text-4xl font-bold text-<%= @user.name_color %>">
      <%= @user.username %>
    </div>
    
    <div class="flex">
      <% if @user.roles.primary %>
        <div class="border-<%= @user.roles.primary.color %> border rounded">
          <div class="text-white text-sm bg-<%= @user.roles.primary.color %> border-white border px-2 italic rounded">
            <%= @user.roles.primary.title %>
          </div>
        </div>
      <% end %>
    </div>

    <table class="table mt-2">
      <% if @user.age %>
        <tr>
          <td>Age</td>
          <td class="font-bold"><%= @user.age.to_i %></td>
        </tr>
      <% end %>

      <% if @user.gender %>
        <tr>
          <td>Gender</td>
          <td class="font-bold">
            <%= @user.gender.humanize %>
          </td>
        </tr>
      <% end %>

      <% if @user.location %>
        <tr>
          <td>Location</td>
          <td class="font-bold"><%= @user.location %></td>
        </tr>
      <% end %>

      <tr>
        <td>Games</td>
        <td class="font-bold"><%= @user.games.count %></td>
      </tr>

      <tr>
        <td>Tutorials</td>
        <td class="font-bold"><%= @user.tutorials.count %></td>
      </tr>

      <tr>
        <td>Resources</td>
        <td class="font-bold"><%= @user.resources.count %></td>
      </tr>

      <tr>
        <td>Replies</td>
        <td class="font-bold"><%= @user.replies.count %></td>
      </tr>
    </table>
  </div>

  <div class="w-1/5 p-2">
    <% if Current.user == @user %>
      <div class="flex justify-end">
        <%= link_to 'Edit Profile', settings_path, class: 'text-green-600 hover:underline' %>
      </div>
    <% end %>

    <div class="mt-2">
      <% @user.featured_recordings.take(3).each do |recording| %>
        <%= link_to recording_path(recording), title: recording.name, class: 'border-red-600 border mb-2 block' do %>
          <div class="border-white border bg-red-600 text-white">
            <%= image_tag recording.avatar, class: 'w-full' %>
          </div>
        <% end %>
      <% end %>
    </div>
  </div>
</div>