config/routes.rb
Rails.application.routes.draw do
  namespace :api do
    scope '/mentions' do
      get '/users', to: 'mentions#users', as: :mentionable_users
      get '/recordings', to: 'mentions#recordings', as: :mentionable_recordings
    end
  end

  get '/todo', to: 'docs#todo'
  get '/faq',  to: 'docs#faq'
  get '/tos',  to: 'docs#tos'

  devise_for :users, path: '', path_names: {
    sign_in: 'login',
    sign_out: 'logout',
    sign_up: 'signup',
  }

  resources :shouts, except: :show do
    member do
      patch '/bump', to: 'shouts#bump', as: :bump
    end
    
    collection do
      patch '/dismiss', to: 'shouts#dismiss', as: :dismiss
    end
  end

  get '/settings', to: 'settings#edit', as: :settings
  patch '/settings', to: 'settings#update'

  resources :tags, only: %i|index show|

  get '/new', to: 'recordings#new', as: :new_recording
  get '/:id/edit', to: 'recordings#edit', as: :edit_recording
  
  get '/@:id', to: 'users#show', as: :user

  resources :replies, only: %i|update destroy|, as: :reply
  resources :recordings, only: %i|create|
  
  # since these are the same route and we can't have duplicate methods
  # we force it to not create one for the later ones and just use them identically
  get '/:id/replies', to: 'replies#show', as: :replies
  post '/:id/replies', to: 'replies#create', as: nil

  get '/:id', to: 'recordings#show', as: :recording
  patch '/:id', to: 'recordings#update'
  
  root to: 'recordings#index'
end

app/helpers/layout_helper.rb
module LayoutHelper
  def outside_of_container
   # TODO 
  end
  
  def dropdown_link_to(name, path, **opts)
    tag.li link_to(name, path, class: 'block py-2 px-4 hover:bg-gray-100', **opts)
  end

  def media(sm:, md:, display: :block)
    <<~HTML.html_safe
      <div class="#{display} md:hidden">
        #{sm}
      </div>

      <div class="hidden md:#{display}">
        #{md}
      </div>
    HTML
  end
end

app/views/layouts/_banner.html.erb
<div class="fixed w-full z-50">
  <% if Shout.show? %>
    <div id="shout" class="flex bg-gray-900 text-white text-center py-1 px-2 font-bold">

      <div class="flex-grow text-center">
        <%= link_to Shout.active.url || '#', class: 'flex justify-center' do %>
          <%= Shout.active.content %> <div class="ml-1">— <%= Shout.active.user.username %></div>
        <% end %>
      </div>

      <% if Current.user %>
        <%= link_to dismiss_shouts_path, method: :patch, remote: true do %>
          <%= fa :times %>
        <% end %>
      <% end %>
    </div>
  <% end %>

  <div class="bg-gray-800 text-white flex items-center font-bold font-display py-2 px-4 shadow-lg">
    <div class="text-white uppercase text-3xl mr-2">
      <%= link_to root_path do %>
        FGH
      <% end %>
    </div>

    <div class="flex">
      <%= link_to root_path(type: 'games'), class: 'mx-2' do %>
        <%= media sm: fa(:gamepad), md: 'Games' %>
      <% end %>

      <%= link_to tags_path, class: 'mx-2' do %>
        <%= media sm: fa(:tags), md: 'Tags' %>
      <% end %>

      <div class="mx-2" data-controller="dropdown">
        <div class="cursor-pointer select-none" data-action="click->dropdown#toggle" data-target="dropdown.button">
          <span class="hidden md:inline">
            More
          </span>

          <%= fa 'caret-down' %>
        </div>

        <div class="w-full md:w-64 bg-white text-black border-2 rounded-lg shadow-lg absolute left-0 hidden" style="top: 50px" data-target="dropdown.menu">
          <ul>
            <%= dropdown_link_to 'Tutorials', root_path(type: 'tutorial') %>
            <%= dropdown_link_to 'Resources', root_path(type: 'resource') %>
            <%= dropdown_link_to 'Shouts', shouts_path %>

            <% if Current.user %>
              <%= dropdown_link_to 'Profile', Current.user %>
              <%= dropdown_link_to 'Log Out', destroy_user_session_path, method: :delete %>
            <% end %>
          </ul>
        </div>
      </div>
    </div>

    <div class="flex-grow"></div>
  
    <div>
      <% if Current.user %>
        <%= link_to Current.user, class: 'flex items-center' do %>
          <%= image_tag Current.user.avatar, class: 'avatar avatar-xs mr-1' %>
          <%= Current.user.username %>
        <% end %>
      <% else %>
        <%= link_to 'Sign Up', new_user_registration_path %>
      <% end %>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<% if @no_body %>
  <%= yield %>
<% else %>
  <!DOCTYPE html>
  <html>
    <head>
      <title>Fgh4</title>
      <%= csrf_meta_tags %>
      <%= csp_meta_tag %>

      <meta name="viewport" content="width=device-width, initial-scale=1">

      <script defer src="https://www.pokecommunity.com/library/fontawesome-pro-5.8.2-web/js/all.min.js"></script>

      <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
      <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
      <%= stylesheet_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    </head>

    <body class="<%= 'shout-showing' if Shout.show? %>">
      <%= rp 'layouts/banner' %>

      <div id="page-wrapper" class="bg-white mb-8">
        <main class="container mx-auto">
          <%= yield %>
        </main>
      </div>
    </body>
  </html>
<% end %>